name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "gym_luckyworld/**"
      - "tests/**"
      - "examples.py"
      - ".github/**"
      - "poetry.lock"
  push:
    branches:
      - main
    paths:
      - "gym_luckyworld/**"
      - "tests/**"
      - "examples.py"
      - ".github/**"
      - "poetry.lock"

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: |
          pipx install poetry && poetry config virtualenvs.in-project true
          echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"

      - name: Install poetry dependencies
        run: |
          poetry install --all-extras

      - name: Test with pytest
        run: |
          pytest tests -v --cov=./gym_luckyworld --durations=0
